apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
    
apiVersion: v1
kind: Pod
metadata:
  name: mosquito
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx

#
Image name: nginx
Key: spray
Value: mortein
Effect: NoSchedule
#
apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    lab: kk
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "spray"
    operator: "Equal"
    value: "mortein"
    effect: "NoSchedule"

































